language: php
php:
    - 5.3.3
    - 5.4
    - 5.5

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - composer self-update
  - composer install --no-interaction --dev

script: phpunit --bootstrap tests/bootstrap.php --stderr tests