language: php
php:
    - "5.3"

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - composer self-update
  - composer install --dev

script: phpunit --bootstrap tests/bootstrap.php --stderr tests